packages:
  - web/
  - functions/modules/**
  - shared-lib/
  - scripts/
  - scripts/utils/**
  - linter-configs/

onlyBuiltDependencies:
  - msw
injectWorkspacePackages: true

syncInjectedDepsAfterScripts:
  - build
