/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { createFileRoute } from '@tanstack/react-router'

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as StandistsImport } from './routes/standists'
import { Route as StaffImport } from './routes/staff'
import { Route as RallyistsImport } from './routes/_rallyists'
import { Route as StandistsIndexImport } from './routes/standists/index'
import { Route as StaffIndexImport } from './routes/staff/index'
import { Route as RallyistsIndexImport } from './routes/_rallyists/index'
import { Route as StandistsQrcodeImport } from './routes/standists/qrcode'
import { Route as StandistsProfileImport } from './routes/standists/profile'
import { Route as StaffWheelImport } from './routes/staff/wheel'
import { Route as StaffStampLinksImport } from './routes/staff/stamp-links'
import { Route as StaffCodeImport } from './routes/staff/code'
import { Route as RallyistsStampImport } from './routes/_rallyists/stamp'
import { Route as RallyistsRulesImport } from './routes/_rallyists/rules'
import { Route as RallyistsWithUserProviderNoAutoAnonymousImport } from './routes/_rallyists/_withUserProviderNoAutoAnonymous'
import { Route as RallyistsWithUserProviderImport } from './routes/_rallyists/_withUserProvider'
import { Route as StaffGenQrcodeIndexImport } from './routes/staff/gen-qrcode/index'
import { Route as RallyistsArtistsIndexImport } from './routes/_rallyists/artists/index'
import { Route as StaffSubmissionSubmissionIdImport } from './routes/staff/submission.$submissionId'
import { Route as StaffGenQrcodeUserIdImport } from './routes/staff/gen-qrcode/$userId'
import { Route as RallyistsCodeTypeImport } from './routes/_rallyists/code.$type'
import { Route as RallyistsWithUserProviderNoAutoAnonymousSettingsImport } from './routes/_rallyists/_withUserProviderNoAutoAnonymous/settings'
import { Route as RallyistsWithUserProviderNoAutoAnonymousLoginImport } from './routes/_rallyists/_withUserProviderNoAutoAnonymous/login'
import { Route as RallyistsWithUserProviderNoAutoAnonymousHandleLoginImport } from './routes/_rallyists/_withUserProviderNoAutoAnonymous/handleLogin'
import { Route as RallyistsWithUserProviderSubmitImport } from './routes/_rallyists/_withUserProvider/submit'

// Create Virtual Routes

const StandistsSigninLazyImport = createFileRoute('/standists/signin')()
const StaffSigninLazyImport = createFileRoute('/staff/signin')()
const RallyistsMapLazyImport = createFileRoute('/_rallyists/map')()

// Create/Update Routes

const StandistsRoute = StandistsImport.update({
  id: '/standists',
  path: '/standists',
  getParentRoute: () => rootRoute,
} as any)

const StaffRoute = StaffImport.update({
  id: '/staff',
  path: '/staff',
  getParentRoute: () => rootRoute,
} as any)

const RallyistsRoute = RallyistsImport.update({
  id: '/_rallyists',
  getParentRoute: () => rootRoute,
} as any)

const StandistsIndexRoute = StandistsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StandistsRoute,
} as any)

const StaffIndexRoute = StaffIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => StaffRoute,
} as any)

const RallyistsIndexRoute = RallyistsIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => RallyistsRoute,
} as any)

const StandistsSigninLazyRoute = StandistsSigninLazyImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => StandistsRoute,
} as any).lazy(() =>
  import('./routes/standists/signin.lazy').then((d) => d.Route),
)

const StaffSigninLazyRoute = StaffSigninLazyImport.update({
  id: '/signin',
  path: '/signin',
  getParentRoute: () => StaffRoute,
} as any).lazy(() => import('./routes/staff/signin.lazy').then((d) => d.Route))

const RallyistsMapLazyRoute = RallyistsMapLazyImport.update({
  id: '/map',
  path: '/map',
  getParentRoute: () => RallyistsRoute,
} as any).lazy(() =>
  import('./routes/_rallyists/map.lazy').then((d) => d.Route),
)

const StandistsQrcodeRoute = StandistsQrcodeImport.update({
  id: '/qrcode',
  path: '/qrcode',
  getParentRoute: () => StandistsRoute,
} as any)

const StandistsProfileRoute = StandistsProfileImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => StandistsRoute,
} as any)

const StaffWheelRoute = StaffWheelImport.update({
  id: '/wheel',
  path: '/wheel',
  getParentRoute: () => StaffRoute,
} as any)

const StaffStampLinksRoute = StaffStampLinksImport.update({
  id: '/stamp-links',
  path: '/stamp-links',
  getParentRoute: () => StaffRoute,
} as any)

const StaffCodeRoute = StaffCodeImport.update({
  id: '/code',
  path: '/code',
  getParentRoute: () => StaffRoute,
} as any)

const RallyistsStampRoute = RallyistsStampImport.update({
  id: '/stamp',
  path: '/stamp',
  getParentRoute: () => RallyistsRoute,
} as any)

const RallyistsRulesRoute = RallyistsRulesImport.update({
  id: '/rules',
  path: '/rules',
  getParentRoute: () => RallyistsRoute,
} as any)

const RallyistsWithUserProviderNoAutoAnonymousRoute =
  RallyistsWithUserProviderNoAutoAnonymousImport.update({
    id: '/_withUserProviderNoAutoAnonymous',
    getParentRoute: () => RallyistsRoute,
  } as any)

const RallyistsWithUserProviderRoute = RallyistsWithUserProviderImport.update({
  id: '/_withUserProvider',
  getParentRoute: () => RallyistsRoute,
} as any)

const StaffGenQrcodeIndexRoute = StaffGenQrcodeIndexImport.update({
  id: '/gen-qrcode/',
  path: '/gen-qrcode/',
  getParentRoute: () => StaffRoute,
} as any)

const RallyistsArtistsIndexRoute = RallyistsArtistsIndexImport.update({
  id: '/artists/',
  path: '/artists/',
  getParentRoute: () => RallyistsRoute,
} as any)

const StaffSubmissionSubmissionIdRoute =
  StaffSubmissionSubmissionIdImport.update({
    id: '/submission/$submissionId',
    path: '/submission/$submissionId',
    getParentRoute: () => StaffRoute,
  } as any)

const StaffGenQrcodeUserIdRoute = StaffGenQrcodeUserIdImport.update({
  id: '/gen-qrcode/$userId',
  path: '/gen-qrcode/$userId',
  getParentRoute: () => StaffRoute,
} as any)

const RallyistsCodeTypeRoute = RallyistsCodeTypeImport.update({
  id: '/code/$type',
  path: '/code/$type',
  getParentRoute: () => RallyistsRoute,
} as any)

const RallyistsWithUserProviderNoAutoAnonymousSettingsRoute =
  RallyistsWithUserProviderNoAutoAnonymousSettingsImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => RallyistsWithUserProviderNoAutoAnonymousRoute,
  } as any)

const RallyistsWithUserProviderNoAutoAnonymousLoginRoute =
  RallyistsWithUserProviderNoAutoAnonymousLoginImport.update({
    id: '/login',
    path: '/login',
    getParentRoute: () => RallyistsWithUserProviderNoAutoAnonymousRoute,
  } as any)

const RallyistsWithUserProviderNoAutoAnonymousHandleLoginRoute =
  RallyistsWithUserProviderNoAutoAnonymousHandleLoginImport.update({
    id: '/handleLogin',
    path: '/handleLogin',
    getParentRoute: () => RallyistsWithUserProviderNoAutoAnonymousRoute,
  } as any)

const RallyistsWithUserProviderSubmitRoute =
  RallyistsWithUserProviderSubmitImport.update({
    id: '/submit',
    path: '/submit',
    getParentRoute: () => RallyistsWithUserProviderRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_rallyists': {
      id: '/_rallyists'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RallyistsImport
      parentRoute: typeof rootRoute
    }
    '/staff': {
      id: '/staff'
      path: '/staff'
      fullPath: '/staff'
      preLoaderRoute: typeof StaffImport
      parentRoute: typeof rootRoute
    }
    '/standists': {
      id: '/standists'
      path: '/standists'
      fullPath: '/standists'
      preLoaderRoute: typeof StandistsImport
      parentRoute: typeof rootRoute
    }
    '/_rallyists/_withUserProvider': {
      id: '/_rallyists/_withUserProvider'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RallyistsWithUserProviderImport
      parentRoute: typeof RallyistsImport
    }
    '/_rallyists/_withUserProviderNoAutoAnonymous': {
      id: '/_rallyists/_withUserProviderNoAutoAnonymous'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof RallyistsWithUserProviderNoAutoAnonymousImport
      parentRoute: typeof RallyistsImport
    }
    '/_rallyists/rules': {
      id: '/_rallyists/rules'
      path: '/rules'
      fullPath: '/rules'
      preLoaderRoute: typeof RallyistsRulesImport
      parentRoute: typeof RallyistsImport
    }
    '/_rallyists/stamp': {
      id: '/_rallyists/stamp'
      path: '/stamp'
      fullPath: '/stamp'
      preLoaderRoute: typeof RallyistsStampImport
      parentRoute: typeof RallyistsImport
    }
    '/staff/code': {
      id: '/staff/code'
      path: '/code'
      fullPath: '/staff/code'
      preLoaderRoute: typeof StaffCodeImport
      parentRoute: typeof StaffImport
    }
    '/staff/stamp-links': {
      id: '/staff/stamp-links'
      path: '/stamp-links'
      fullPath: '/staff/stamp-links'
      preLoaderRoute: typeof StaffStampLinksImport
      parentRoute: typeof StaffImport
    }
    '/staff/wheel': {
      id: '/staff/wheel'
      path: '/wheel'
      fullPath: '/staff/wheel'
      preLoaderRoute: typeof StaffWheelImport
      parentRoute: typeof StaffImport
    }
    '/standists/profile': {
      id: '/standists/profile'
      path: '/profile'
      fullPath: '/standists/profile'
      preLoaderRoute: typeof StandistsProfileImport
      parentRoute: typeof StandistsImport
    }
    '/standists/qrcode': {
      id: '/standists/qrcode'
      path: '/qrcode'
      fullPath: '/standists/qrcode'
      preLoaderRoute: typeof StandistsQrcodeImport
      parentRoute: typeof StandistsImport
    }
    '/_rallyists/map': {
      id: '/_rallyists/map'
      path: '/map'
      fullPath: '/map'
      preLoaderRoute: typeof RallyistsMapLazyImport
      parentRoute: typeof RallyistsImport
    }
    '/staff/signin': {
      id: '/staff/signin'
      path: '/signin'
      fullPath: '/staff/signin'
      preLoaderRoute: typeof StaffSigninLazyImport
      parentRoute: typeof StaffImport
    }
    '/standists/signin': {
      id: '/standists/signin'
      path: '/signin'
      fullPath: '/standists/signin'
      preLoaderRoute: typeof StandistsSigninLazyImport
      parentRoute: typeof StandistsImport
    }
    '/_rallyists/': {
      id: '/_rallyists/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof RallyistsIndexImport
      parentRoute: typeof RallyistsImport
    }
    '/staff/': {
      id: '/staff/'
      path: '/'
      fullPath: '/staff/'
      preLoaderRoute: typeof StaffIndexImport
      parentRoute: typeof StaffImport
    }
    '/standists/': {
      id: '/standists/'
      path: '/'
      fullPath: '/standists/'
      preLoaderRoute: typeof StandistsIndexImport
      parentRoute: typeof StandistsImport
    }
    '/_rallyists/_withUserProvider/submit': {
      id: '/_rallyists/_withUserProvider/submit'
      path: '/submit'
      fullPath: '/submit'
      preLoaderRoute: typeof RallyistsWithUserProviderSubmitImport
      parentRoute: typeof RallyistsWithUserProviderImport
    }
    '/_rallyists/_withUserProviderNoAutoAnonymous/handleLogin': {
      id: '/_rallyists/_withUserProviderNoAutoAnonymous/handleLogin'
      path: '/handleLogin'
      fullPath: '/handleLogin'
      preLoaderRoute: typeof RallyistsWithUserProviderNoAutoAnonymousHandleLoginImport
      parentRoute: typeof RallyistsWithUserProviderNoAutoAnonymousImport
    }
    '/_rallyists/_withUserProviderNoAutoAnonymous/login': {
      id: '/_rallyists/_withUserProviderNoAutoAnonymous/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof RallyistsWithUserProviderNoAutoAnonymousLoginImport
      parentRoute: typeof RallyistsWithUserProviderNoAutoAnonymousImport
    }
    '/_rallyists/_withUserProviderNoAutoAnonymous/settings': {
      id: '/_rallyists/_withUserProviderNoAutoAnonymous/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof RallyistsWithUserProviderNoAutoAnonymousSettingsImport
      parentRoute: typeof RallyistsWithUserProviderNoAutoAnonymousImport
    }
    '/_rallyists/code/$type': {
      id: '/_rallyists/code/$type'
      path: '/code/$type'
      fullPath: '/code/$type'
      preLoaderRoute: typeof RallyistsCodeTypeImport
      parentRoute: typeof RallyistsImport
    }
    '/staff/gen-qrcode/$userId': {
      id: '/staff/gen-qrcode/$userId'
      path: '/gen-qrcode/$userId'
      fullPath: '/staff/gen-qrcode/$userId'
      preLoaderRoute: typeof StaffGenQrcodeUserIdImport
      parentRoute: typeof StaffImport
    }
    '/staff/submission/$submissionId': {
      id: '/staff/submission/$submissionId'
      path: '/submission/$submissionId'
      fullPath: '/staff/submission/$submissionId'
      preLoaderRoute: typeof StaffSubmissionSubmissionIdImport
      parentRoute: typeof StaffImport
    }
    '/_rallyists/artists/': {
      id: '/_rallyists/artists/'
      path: '/artists'
      fullPath: '/artists'
      preLoaderRoute: typeof RallyistsArtistsIndexImport
      parentRoute: typeof RallyistsImport
    }
    '/staff/gen-qrcode/': {
      id: '/staff/gen-qrcode/'
      path: '/gen-qrcode'
      fullPath: '/staff/gen-qrcode'
      preLoaderRoute: typeof StaffGenQrcodeIndexImport
      parentRoute: typeof StaffImport
    }
  }
}

// Create and export the route tree

interface RallyistsWithUserProviderRouteChildren {
  RallyistsWithUserProviderSubmitRoute: typeof RallyistsWithUserProviderSubmitRoute
}

const RallyistsWithUserProviderRouteChildren: RallyistsWithUserProviderRouteChildren =
  {
    RallyistsWithUserProviderSubmitRoute: RallyistsWithUserProviderSubmitRoute,
  }

const RallyistsWithUserProviderRouteWithChildren =
  RallyistsWithUserProviderRoute._addFileChildren(
    RallyistsWithUserProviderRouteChildren,
  )

interface RallyistsWithUserProviderNoAutoAnonymousRouteChildren {
  RallyistsWithUserProviderNoAutoAnonymousHandleLoginRoute: typeof RallyistsWithUserProviderNoAutoAnonymousHandleLoginRoute
  RallyistsWithUserProviderNoAutoAnonymousLoginRoute: typeof RallyistsWithUserProviderNoAutoAnonymousLoginRoute
  RallyistsWithUserProviderNoAutoAnonymousSettingsRoute: typeof RallyistsWithUserProviderNoAutoAnonymousSettingsRoute
}

const RallyistsWithUserProviderNoAutoAnonymousRouteChildren: RallyistsWithUserProviderNoAutoAnonymousRouteChildren =
  {
    RallyistsWithUserProviderNoAutoAnonymousHandleLoginRoute:
      RallyistsWithUserProviderNoAutoAnonymousHandleLoginRoute,
    RallyistsWithUserProviderNoAutoAnonymousLoginRoute:
      RallyistsWithUserProviderNoAutoAnonymousLoginRoute,
    RallyistsWithUserProviderNoAutoAnonymousSettingsRoute:
      RallyistsWithUserProviderNoAutoAnonymousSettingsRoute,
  }

const RallyistsWithUserProviderNoAutoAnonymousRouteWithChildren =
  RallyistsWithUserProviderNoAutoAnonymousRoute._addFileChildren(
    RallyistsWithUserProviderNoAutoAnonymousRouteChildren,
  )

interface RallyistsRouteChildren {
  RallyistsWithUserProviderRoute: typeof RallyistsWithUserProviderRouteWithChildren
  RallyistsWithUserProviderNoAutoAnonymousRoute: typeof RallyistsWithUserProviderNoAutoAnonymousRouteWithChildren
  RallyistsRulesRoute: typeof RallyistsRulesRoute
  RallyistsStampRoute: typeof RallyistsStampRoute
  RallyistsMapLazyRoute: typeof RallyistsMapLazyRoute
  RallyistsIndexRoute: typeof RallyistsIndexRoute
  RallyistsCodeTypeRoute: typeof RallyistsCodeTypeRoute
  RallyistsArtistsIndexRoute: typeof RallyistsArtistsIndexRoute
}

const RallyistsRouteChildren: RallyistsRouteChildren = {
  RallyistsWithUserProviderRoute: RallyistsWithUserProviderRouteWithChildren,
  RallyistsWithUserProviderNoAutoAnonymousRoute:
    RallyistsWithUserProviderNoAutoAnonymousRouteWithChildren,
  RallyistsRulesRoute: RallyistsRulesRoute,
  RallyistsStampRoute: RallyistsStampRoute,
  RallyistsMapLazyRoute: RallyistsMapLazyRoute,
  RallyistsIndexRoute: RallyistsIndexRoute,
  RallyistsCodeTypeRoute: RallyistsCodeTypeRoute,
  RallyistsArtistsIndexRoute: RallyistsArtistsIndexRoute,
}

const RallyistsRouteWithChildren = RallyistsRoute._addFileChildren(
  RallyistsRouteChildren,
)

interface StaffRouteChildren {
  StaffCodeRoute: typeof StaffCodeRoute
  StaffStampLinksRoute: typeof StaffStampLinksRoute
  StaffWheelRoute: typeof StaffWheelRoute
  StaffSigninLazyRoute: typeof StaffSigninLazyRoute
  StaffIndexRoute: typeof StaffIndexRoute
  StaffGenQrcodeUserIdRoute: typeof StaffGenQrcodeUserIdRoute
  StaffSubmissionSubmissionIdRoute: typeof StaffSubmissionSubmissionIdRoute
  StaffGenQrcodeIndexRoute: typeof StaffGenQrcodeIndexRoute
}

const StaffRouteChildren: StaffRouteChildren = {
  StaffCodeRoute: StaffCodeRoute,
  StaffStampLinksRoute: StaffStampLinksRoute,
  StaffWheelRoute: StaffWheelRoute,
  StaffSigninLazyRoute: StaffSigninLazyRoute,
  StaffIndexRoute: StaffIndexRoute,
  StaffGenQrcodeUserIdRoute: StaffGenQrcodeUserIdRoute,
  StaffSubmissionSubmissionIdRoute: StaffSubmissionSubmissionIdRoute,
  StaffGenQrcodeIndexRoute: StaffGenQrcodeIndexRoute,
}

const StaffRouteWithChildren = StaffRoute._addFileChildren(StaffRouteChildren)

interface StandistsRouteChildren {
  StandistsProfileRoute: typeof StandistsProfileRoute
  StandistsQrcodeRoute: typeof StandistsQrcodeRoute
  StandistsSigninLazyRoute: typeof StandistsSigninLazyRoute
  StandistsIndexRoute: typeof StandistsIndexRoute
}

const StandistsRouteChildren: StandistsRouteChildren = {
  StandistsProfileRoute: StandistsProfileRoute,
  StandistsQrcodeRoute: StandistsQrcodeRoute,
  StandistsSigninLazyRoute: StandistsSigninLazyRoute,
  StandistsIndexRoute: StandistsIndexRoute,
}

const StandistsRouteWithChildren = StandistsRoute._addFileChildren(
  StandistsRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof RallyistsWithUserProviderNoAutoAnonymousRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/standists': typeof StandistsRouteWithChildren
  '/rules': typeof RallyistsRulesRoute
  '/stamp': typeof RallyistsStampRoute
  '/staff/code': typeof StaffCodeRoute
  '/staff/stamp-links': typeof StaffStampLinksRoute
  '/staff/wheel': typeof StaffWheelRoute
  '/standists/profile': typeof StandistsProfileRoute
  '/standists/qrcode': typeof StandistsQrcodeRoute
  '/map': typeof RallyistsMapLazyRoute
  '/staff/signin': typeof StaffSigninLazyRoute
  '/standists/signin': typeof StandistsSigninLazyRoute
  '/': typeof RallyistsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/standists/': typeof StandistsIndexRoute
  '/submit': typeof RallyistsWithUserProviderSubmitRoute
  '/handleLogin': typeof RallyistsWithUserProviderNoAutoAnonymousHandleLoginRoute
  '/login': typeof RallyistsWithUserProviderNoAutoAnonymousLoginRoute
  '/settings': typeof RallyistsWithUserProviderNoAutoAnonymousSettingsRoute
  '/code/$type': typeof RallyistsCodeTypeRoute
  '/staff/gen-qrcode/$userId': typeof StaffGenQrcodeUserIdRoute
  '/staff/submission/$submissionId': typeof StaffSubmissionSubmissionIdRoute
  '/artists': typeof RallyistsArtistsIndexRoute
  '/staff/gen-qrcode': typeof StaffGenQrcodeIndexRoute
}

export interface FileRoutesByTo {
  '': typeof RallyistsWithUserProviderNoAutoAnonymousRouteWithChildren
  '/rules': typeof RallyistsRulesRoute
  '/stamp': typeof RallyistsStampRoute
  '/staff/code': typeof StaffCodeRoute
  '/staff/stamp-links': typeof StaffStampLinksRoute
  '/staff/wheel': typeof StaffWheelRoute
  '/standists/profile': typeof StandistsProfileRoute
  '/standists/qrcode': typeof StandistsQrcodeRoute
  '/map': typeof RallyistsMapLazyRoute
  '/staff/signin': typeof StaffSigninLazyRoute
  '/standists/signin': typeof StandistsSigninLazyRoute
  '/': typeof RallyistsIndexRoute
  '/staff': typeof StaffIndexRoute
  '/standists': typeof StandistsIndexRoute
  '/submit': typeof RallyistsWithUserProviderSubmitRoute
  '/handleLogin': typeof RallyistsWithUserProviderNoAutoAnonymousHandleLoginRoute
  '/login': typeof RallyistsWithUserProviderNoAutoAnonymousLoginRoute
  '/settings': typeof RallyistsWithUserProviderNoAutoAnonymousSettingsRoute
  '/code/$type': typeof RallyistsCodeTypeRoute
  '/staff/gen-qrcode/$userId': typeof StaffGenQrcodeUserIdRoute
  '/staff/submission/$submissionId': typeof StaffSubmissionSubmissionIdRoute
  '/artists': typeof RallyistsArtistsIndexRoute
  '/staff/gen-qrcode': typeof StaffGenQrcodeIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_rallyists': typeof RallyistsRouteWithChildren
  '/staff': typeof StaffRouteWithChildren
  '/standists': typeof StandistsRouteWithChildren
  '/_rallyists/_withUserProvider': typeof RallyistsWithUserProviderRouteWithChildren
  '/_rallyists/_withUserProviderNoAutoAnonymous': typeof RallyistsWithUserProviderNoAutoAnonymousRouteWithChildren
  '/_rallyists/rules': typeof RallyistsRulesRoute
  '/_rallyists/stamp': typeof RallyistsStampRoute
  '/staff/code': typeof StaffCodeRoute
  '/staff/stamp-links': typeof StaffStampLinksRoute
  '/staff/wheel': typeof StaffWheelRoute
  '/standists/profile': typeof StandistsProfileRoute
  '/standists/qrcode': typeof StandistsQrcodeRoute
  '/_rallyists/map': typeof RallyistsMapLazyRoute
  '/staff/signin': typeof StaffSigninLazyRoute
  '/standists/signin': typeof StandistsSigninLazyRoute
  '/_rallyists/': typeof RallyistsIndexRoute
  '/staff/': typeof StaffIndexRoute
  '/standists/': typeof StandistsIndexRoute
  '/_rallyists/_withUserProvider/submit': typeof RallyistsWithUserProviderSubmitRoute
  '/_rallyists/_withUserProviderNoAutoAnonymous/handleLogin': typeof RallyistsWithUserProviderNoAutoAnonymousHandleLoginRoute
  '/_rallyists/_withUserProviderNoAutoAnonymous/login': typeof RallyistsWithUserProviderNoAutoAnonymousLoginRoute
  '/_rallyists/_withUserProviderNoAutoAnonymous/settings': typeof RallyistsWithUserProviderNoAutoAnonymousSettingsRoute
  '/_rallyists/code/$type': typeof RallyistsCodeTypeRoute
  '/staff/gen-qrcode/$userId': typeof StaffGenQrcodeUserIdRoute
  '/staff/submission/$submissionId': typeof StaffSubmissionSubmissionIdRoute
  '/_rallyists/artists/': typeof RallyistsArtistsIndexRoute
  '/staff/gen-qrcode/': typeof StaffGenQrcodeIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | ''
    | '/staff'
    | '/standists'
    | '/rules'
    | '/stamp'
    | '/staff/code'
    | '/staff/stamp-links'
    | '/staff/wheel'
    | '/standists/profile'
    | '/standists/qrcode'
    | '/map'
    | '/staff/signin'
    | '/standists/signin'
    | '/'
    | '/staff/'
    | '/standists/'
    | '/submit'
    | '/handleLogin'
    | '/login'
    | '/settings'
    | '/code/$type'
    | '/staff/gen-qrcode/$userId'
    | '/staff/submission/$submissionId'
    | '/artists'
    | '/staff/gen-qrcode'
  fileRoutesByTo: FileRoutesByTo
  to:
    | ''
    | '/rules'
    | '/stamp'
    | '/staff/code'
    | '/staff/stamp-links'
    | '/staff/wheel'
    | '/standists/profile'
    | '/standists/qrcode'
    | '/map'
    | '/staff/signin'
    | '/standists/signin'
    | '/'
    | '/staff'
    | '/standists'
    | '/submit'
    | '/handleLogin'
    | '/login'
    | '/settings'
    | '/code/$type'
    | '/staff/gen-qrcode/$userId'
    | '/staff/submission/$submissionId'
    | '/artists'
    | '/staff/gen-qrcode'
  id:
    | '__root__'
    | '/_rallyists'
    | '/staff'
    | '/standists'
    | '/_rallyists/_withUserProvider'
    | '/_rallyists/_withUserProviderNoAutoAnonymous'
    | '/_rallyists/rules'
    | '/_rallyists/stamp'
    | '/staff/code'
    | '/staff/stamp-links'
    | '/staff/wheel'
    | '/standists/profile'
    | '/standists/qrcode'
    | '/_rallyists/map'
    | '/staff/signin'
    | '/standists/signin'
    | '/_rallyists/'
    | '/staff/'
    | '/standists/'
    | '/_rallyists/_withUserProvider/submit'
    | '/_rallyists/_withUserProviderNoAutoAnonymous/handleLogin'
    | '/_rallyists/_withUserProviderNoAutoAnonymous/login'
    | '/_rallyists/_withUserProviderNoAutoAnonymous/settings'
    | '/_rallyists/code/$type'
    | '/staff/gen-qrcode/$userId'
    | '/staff/submission/$submissionId'
    | '/_rallyists/artists/'
    | '/staff/gen-qrcode/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  RallyistsRoute: typeof RallyistsRouteWithChildren
  StaffRoute: typeof StaffRouteWithChildren
  StandistsRoute: typeof StandistsRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  RallyistsRoute: RallyistsRouteWithChildren,
  StaffRoute: StaffRouteWithChildren,
  StandistsRoute: StandistsRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_rallyists",
        "/staff",
        "/standists"
      ]
    },
    "/_rallyists": {
      "filePath": "_rallyists.tsx",
      "children": [
        "/_rallyists/_withUserProvider",
        "/_rallyists/_withUserProviderNoAutoAnonymous",
        "/_rallyists/rules",
        "/_rallyists/stamp",
        "/_rallyists/map",
        "/_rallyists/",
        "/_rallyists/code/$type",
        "/_rallyists/artists/"
      ]
    },
    "/staff": {
      "filePath": "staff.tsx",
      "children": [
        "/staff/code",
        "/staff/stamp-links",
        "/staff/wheel",
        "/staff/signin",
        "/staff/",
        "/staff/gen-qrcode/$userId",
        "/staff/submission/$submissionId",
        "/staff/gen-qrcode/"
      ]
    },
    "/standists": {
      "filePath": "standists.tsx",
      "children": [
        "/standists/profile",
        "/standists/qrcode",
        "/standists/signin",
        "/standists/"
      ]
    },
    "/_rallyists/_withUserProvider": {
      "filePath": "_rallyists/_withUserProvider.tsx",
      "parent": "/_rallyists",
      "children": [
        "/_rallyists/_withUserProvider/submit"
      ]
    },
    "/_rallyists/_withUserProviderNoAutoAnonymous": {
      "filePath": "_rallyists/_withUserProviderNoAutoAnonymous.tsx",
      "parent": "/_rallyists",
      "children": [
        "/_rallyists/_withUserProviderNoAutoAnonymous/handleLogin",
        "/_rallyists/_withUserProviderNoAutoAnonymous/login",
        "/_rallyists/_withUserProviderNoAutoAnonymous/settings"
      ]
    },
    "/_rallyists/rules": {
      "filePath": "_rallyists/rules.tsx",
      "parent": "/_rallyists"
    },
    "/_rallyists/stamp": {
      "filePath": "_rallyists/stamp.tsx",
      "parent": "/_rallyists"
    },
    "/staff/code": {
      "filePath": "staff/code.tsx",
      "parent": "/staff"
    },
    "/staff/stamp-links": {
      "filePath": "staff/stamp-links.tsx",
      "parent": "/staff"
    },
    "/staff/wheel": {
      "filePath": "staff/wheel.tsx",
      "parent": "/staff"
    },
    "/standists/profile": {
      "filePath": "standists/profile.tsx",
      "parent": "/standists"
    },
    "/standists/qrcode": {
      "filePath": "standists/qrcode.tsx",
      "parent": "/standists"
    },
    "/_rallyists/map": {
      "filePath": "_rallyists/map.lazy.tsx",
      "parent": "/_rallyists"
    },
    "/staff/signin": {
      "filePath": "staff/signin.lazy.tsx",
      "parent": "/staff"
    },
    "/standists/signin": {
      "filePath": "standists/signin.lazy.tsx",
      "parent": "/standists"
    },
    "/_rallyists/": {
      "filePath": "_rallyists/index.tsx",
      "parent": "/_rallyists"
    },
    "/staff/": {
      "filePath": "staff/index.tsx",
      "parent": "/staff"
    },
    "/standists/": {
      "filePath": "standists/index.tsx",
      "parent": "/standists"
    },
    "/_rallyists/_withUserProvider/submit": {
      "filePath": "_rallyists/_withUserProvider/submit.tsx",
      "parent": "/_rallyists/_withUserProvider"
    },
    "/_rallyists/_withUserProviderNoAutoAnonymous/handleLogin": {
      "filePath": "_rallyists/_withUserProviderNoAutoAnonymous/handleLogin.tsx",
      "parent": "/_rallyists/_withUserProviderNoAutoAnonymous"
    },
    "/_rallyists/_withUserProviderNoAutoAnonymous/login": {
      "filePath": "_rallyists/_withUserProviderNoAutoAnonymous/login.tsx",
      "parent": "/_rallyists/_withUserProviderNoAutoAnonymous"
    },
    "/_rallyists/_withUserProviderNoAutoAnonymous/settings": {
      "filePath": "_rallyists/_withUserProviderNoAutoAnonymous/settings.tsx",
      "parent": "/_rallyists/_withUserProviderNoAutoAnonymous"
    },
    "/_rallyists/code/$type": {
      "filePath": "_rallyists/code.$type.tsx",
      "parent": "/_rallyists"
    },
    "/staff/gen-qrcode/$userId": {
      "filePath": "staff/gen-qrcode/$userId.tsx",
      "parent": "/staff"
    },
    "/staff/submission/$submissionId": {
      "filePath": "staff/submission.$submissionId.tsx",
      "parent": "/staff"
    },
    "/_rallyists/artists/": {
      "filePath": "_rallyists/artists/index.tsx",
      "parent": "/_rallyists"
    },
    "/staff/gen-qrcode/": {
      "filePath": "staff/gen-qrcode/index.tsx",
      "parent": "/staff"
    }
  }
}
ROUTE_MANIFEST_END */
