import { initializeApp } from "firebase/app";
import { getMessaging, onBackgroundMessage } from "firebase/messaging/sw";
import { CacheableResponsePlugin } from "workbox-cacheable-response";
import { clientsClaim } from "workbox-core";
import { ExpirationPlugin } from "workbox-expiration";
import { cleanupOutdatedCaches, precacheAndRoute } from "workbox-precaching";
import { registerRoute } from "workbox-routing";
import { StaleWhileRevalidate } from "workbox-strategies";

declare let self: ServiceWorkerGlobalScope;

cleanupOutdatedCaches();

// Pre-cache all assets from workbox manifest (generated by vite-plugin-pwa)
precacheAndRoute(self.__WB_MANIFEST);

registerRoute(
  ({ url }) => /v1\/storage\/buckets/.test(url.pathname),
  new StaleWhileRevalidate({
    cacheName: "rally-assets",
    plugins: [
      new CacheableResponsePlugin({
        statuses: [0, 200],
      }),
      new ExpirationPlugin({
        maxEntries: 100,
        maxAgeSeconds: 60 * 60 * 72,
      }),
    ],
  }),
);

// Firebase hello!
const firebaseConfig = {
  apiKey: "AIzaSyBb4D9QQpeHG2v_7Yxf4DR0rVvD24eMdi0",
  authDomain: "vtuberstamprally.firebaseapp.com",
  projectId: "vtuberstamprally",
  storageBucket: "vtuberstamprally.firebasestorage.app",
  messagingSenderId: "689328750745",
  appId: "1:689328750745:web:636031de1e4b3c4d493808",
};

const app = initializeApp(firebaseConfig);
const messaging = getMessaging(app);

onBackgroundMessage(messaging, console.log);

// Claim clients and activate the service worker
self.skipWaiting();
clientsClaim();
