name: Lint

on:
  push:
    paths:
      - "web/**"
      - "pnpm-lock.yaml"
  workflow_dispatch:

permissions:
  contents: read

jobs:
  lint:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          run_install: true

      - name: "pnpm run lint"
        run: pnpm run -r --parallel lint

  style:
    name: Check style (Prettier)

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          run_install: true

      - name: "pnpm run prettier:check"
        run: pnpm run -r --parallel prettier:check

  test:
    name: Test web

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          run_install: true

      - name: "web: pnpm test"
        run: pnpm --filter=web test

  build:
    name: Build web

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          run_install: true

      - name: "web: pnpm build"
        env:
          NODE_ENV: production
          VITE_PUBLIC_URL: https://example.com
          VITE_APPWRITE_ENDPOINT: https://appwrite.example.com
          VITE_APPWRITE_PROJECT_ID: example
          VITE_APPWRITE_NOTIFICATION_PROVIDER_ID: example
          VITE_DATABASE_ID: example
          VITE_EVENT_END_DATE: example
          VITE_STAMPS_TO_COLLECT: 10
          VITE_STANDISTS_COLLECTION_ID: example
          VITE_SUBMISSIONS_COLLECTION_ID: example
          VITE_SUBMIT_FUNCTION_ID: example
          VITE_WHEEL_COLLECTION_ID: example
          VITE_GET_PRIVATE_KEY_FUNCTION_ID: example
          VITE_KV_COLLECTION_ID: example
          VITE_ASSETS_BUCKET_ID: example
          VITE_CONTEST_PARTICIPANTS_COLLECTION_ID: example
          VITE_FIREBASE_API_KEY: example
          VITE_FIREBASE_AUTH_DOMAIN: example
          VITE_FIREBASE_PROJECT_ID: example
          VITE_FIREBASE_STORAGE_BUCKET: example
          VITE_FIREBASE_MESSAGING_SENDER_ID: example
          VITE_FIREBASE_APP_ID: example
          VITE_FIREBASE_VAPID_PUBLIC_KEY: example
          VITE_SENTRY_DSN: unknown
          VITE_SENTRY_ENVIRONMENT: ci
        run: pnpm --filter=web build

      # upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: web/dist/
