name: Lint

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test:
    name: Lint

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9
          run_install: true

      - name: 'web: pnpm lint'
        run: cd web && pnpm lint