name: Lint

on:
  push:
    paths:
      - 'web/**'
  workflow_dispatch:
  

permissions:
  contents: read

jobs:
  lint:
    name: Lint web

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          run_install: true

      - name: 'web: pnpm lint'
        run: cd web && pnpm lint

  test:
    name: Test web

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          run_install: true

      - name: 'web: pnpm test'
        run: pnpm --filter web test

  style:
    name: Check style (Prettier)

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          run_install: true

      - name: 'web: pnpm prettier:check'
        run: pnpm --filter web prettier:check


  build:
    name: Build web

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          run_install: true

      - name: 'web: pnpm build'
        run: pnpm --filter web build

    # upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: web/dist/
