name: Lint

on:
  - push
  - pull_request
  - workflow_dispatch

jobs:
  test:
    name: Lint web

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9
          run_install: true

      - name: 'web: pnpm lint'
        run: cd web && pnpm lint

  build:
    name: Build web

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9
          run_install: true

      - name: 'web: pnpm build'
        run: cd web && pnpm build

    # upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: web-dist
          path: web/dist/
