name: Storybook

on:
  push:
    paths:
      - web/src/**
      - web/.storybook/**
      - web/package.json
      - pnpm-lock.yaml
    branches:
      - main

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-deploy-storybook:
    name: Build and deploy Storybook

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          run_install: true

      - name: build-publish
        uses: bitovi/github-actions-storybook-to-github-pages@v1.0.3
        with:
          checkout: false
          install_command: pnpm --filter web install
          build_command: pnpm --filter web build-storybook
          path: web/storybook-static
