name: Storybook

on:
  - push
  - pull_request

jobs:
  test:
    name: Build

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup pnpm
        uses: pnpm/action-setup@v4.0.0
        with:
          version: 9
          run_install: true

      - name: 'web: pnpm build-storybook'
        run: pnpm --filter web build-storybook

      # upload artifacts
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: storybook-static
          path: web/storybook-static/
